name: Bug report
description: Report a reproducible problem in kubeforward.
title: "[bug]: "
labels:
  - type:bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Keep this actionable and reproducible.
  - type: input
    id: version
    attributes:
      label: Kubeforward version
      description: Output of `kubeforward --version`.
      placeholder: v0.1.0
    validations:
      required: true
  - type: input
    id: k8s_context
    attributes:
      label: Kubernetes context
      description: Output of `kubectl config current-context`.
      placeholder: my-cluster-prod
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal, deterministic steps.
      placeholder: |
        1. Run ...
        2. Run ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or output
      description: Paste command output and errors.
      render: shell
