name: Feature request
description: Propose a new capability or behavior change.
title: "[feature]: "
labels:
  - type:feature
body:
  - type: markdown
    attributes:
      value: |
        Describe the problem first, then the proposal.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What is broken or inefficient today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Be explicit about CLI behavior and config shape.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What did you reject and why?
  - type: textarea
    id: impact
    attributes:
      label: Impact and risks
      description: Include breaking changes, migration, and ops impact.
